### ISSUE TITLE
Investigate why HTML Select elements are not working

### ISSUE THREAD

**Issue by kensplanet** [kensplanet/browser-automation-toolkit#23]
![image](https://cloud.githubusercontent.com/assets/4705188/16568483/ba783b88-41f8-11e6-9649-a0fb6ad7bd7d.png)

**Comment by bobesku** [comment]
Hello, I have tested again, and although it records the actions properly for "select" html elements, the `replay` does not affect them. I thought that maybe there is a specific issue with the websites that I am testing, so tried on the w3schools.com (http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select) and still not working. Please take a look, maybe there is a chance to fix this. See attached screenshot with the element that I have tested. All the best.
![screenshot_20160916_004620](https://cloud.githubusercontent.com/assets/17592925/18568766/7bedc250-7ba7-11e6-8ab4-19cb88647555.png)
